package com.khaleo.flashcard.service.auth;

public enum AuthErrorCode {
    INVALID_REQUEST,
    DUPLICATE_EMAIL,
    INVALID_VERIFICATION_TOKEN,
    EXPIRED_VERIFICATION_TOKEN,
    UNVERIFIED_EMAIL,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    BANNED_USER_REQUEST_DENIED,
    INVALID_REFRESH_TOKEN,
    EXPIRED_REFRESH_TOKEN,
    INVALID_RESET_TOKEN,
    EXPIRED_RESET_TOKEN
}
