spring:
  application:
    name: flashcard-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/khaleo_flashcard}
    username: ${DB_USERNAME:khaleo}
    password: ${DB_PASSWORD:khaleo}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  dynamo:
    region: ${AWS_REGION:us-east-1}
    endpoint: ${DYNAMODB_ENDPOINT:}
    study-activity-log-table: ${STUDY_ACTIVITY_LOG_TABLE:StudyActivityLog}
